#!/bin/bash
#=================================================================================================|
#
#   Copyright (c) 2011-2013, Marsh Ray
#
#   Permission to use, copy, modify, and/or distribute this software for any
#   purpose with or without fee is hereby granted, provided that the above
#   copyright notice and this permission notice appear in all copies.
#
#   THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#   WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#   MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#   ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#   WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#   ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
#   OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
#=================================================================================================|

set -o errexit
#set -o xtrace

source $(dirname $(readlink -n -f "$0"))/zz-build-config "$@"

#	Command-line options.
unset -v NO_TEST
for arg in '--debug' "$@"
do
	if [[ "$arg" == "--debug" || "$arg" == "--release" || "$arg" == "--profile" ]]; then
		unset NULL; # handled already
	elif [[ "$arg" == "--no-test" ]]; then
		NO_TEST="--no-test"
	elif [[ "$arg" == "--help" ]]; then
		echo "Other valid command-line arguments are --debug, --release, --profile, and --no-test."
		exit 1
	else
		echo "Unrecognized command-line argument: $arg"
		exit 1
	fi
done

SUCCESS_FLAG=$QAK_BUILD_DIR/success.out
if [[ -f "$SUCCESS_FLAG" ]]; then rm "$SUCCESS_FLAG"; fi

echo '----------------------------------------------------------------------'

(make --no-print-directory -C "$QAK_BUILD_DIR" && touch "$SUCCESS_FLAG")\
|& grep -v 'In file included from'
#	Vim doesn't handle ^^^ this one error message format well currently.

if [[ ! -f "$SUCCESS_FLAG" ]]; then
	exit 1
fi

if [[ -z "$NO_TEST" ]]; then
	CTEST_OUTPUT_ON_FAILURE=1
	export CTEST_OUTPUT_ON_FAILURE
	
	#	Call make test via 'nice' in case a test starts running away with system resources.
	nice -n 10 make -C "$QAK_BUILD_DIR" test
fi
